
project_id = "fndkivztnbkzuqosmbdx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true

[functions]
[functions.distribute-commission]
verify_jwt = true
